steps:
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=secrets-controller"]
    args: ["install", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/secrets-controller:0.0.3", "."]

images: ["gcr.io/${PROJECT_ID}/secrets-controller:0.0.3"]
