apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: secrets-controller
  labels:
    app: secrets-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: secrets-controller
    spec:
      containers:
        - name: secrets-controller
          image: gcr.io/hightowerlabs/secrets-controller:0.0.3
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "-namespace=$(NAMESPACE)"
            - "-secretName=oscon"
            - "-vault-addr=http://vault-0.vault.$(NAMESPACE).svc.cluster.local:8200"
            - "-vault-token=3e4a5ba1-oscon-422b-d1db-844979cab098"
          resources:
            requests:
              cpu: 100m
              memory: 10Mi
          imagePullPolicy: Always
